Repository tonybaloney/vscode-pets, pull requests merged in 2022-10, with the labels that each got.

#155 I added Jemima, Bolty and Beaky
  src/common/names.ts
Labels: hacktoberfest-accepted

#156 I have added Hissy Elliot
  src/common/names.ts
Labels: hacktoberfest-accepted

#158 Added Kanye nest
  src/common/names.ts
Labels: hacktoberfest-accepted

#160 Add Dame Judi Finch
  src/common/names.ts
Labels: hacktoberfest-accepted

#159 I added Baquack Obama
  src/common/names.ts
Labels: hacktoberfest-accepted

#163 Removed 'Purfect' from DOG NAMES
  src/common/names.ts
Labels: hacktoberfest-accepted

#164 removed the un-cat names
  src/common/names.ts
Labels: hacktoberfest-accepted

#166 Removed some un-dog-like names
  src/common/names.ts
Labels: hacktoberfest-accepted

#167 Throttling frame rate for consistent ball animation
  src/panel/main.ts
Labels: hacktoberfest-accepted

#169 add: new dog name called 'Ein'
  src/common/names.ts
Labels: hacktoberfest-accepted

#170 names: Add New cat name
  src/common/names.ts
Labels: hacktoberfest-accepted

#171 Add links to contributors' section
  README.md
Labels: hacktoberfest-accepted

#174 added Maddy as Dog and Jelly Beans as Duck
  src/common/names.ts
Labels: hacktoberfest-accepted

#178 (names.ts) add crab names
  src/common/names.ts
Labels: hacktoberfest-accepted

#175 Roll Call
  media/main-bundle.js
  package.json
  src/extension/extension.ts
  src/panel/main.ts
  src/panel/pets.ts
Labels: hacktoberfest-accepted

#176 Add the ability to set a custom name for a pet
  media/main-bundle.js
  src/common/names.ts
  src/extension/extension.ts
  src/panel/main.ts
  src/panel/pets.ts
Labels: hacktoberfest-accepted

#182 Fix Pet's not spawning when cancelling the operation.
  media/main-bundle.js
  src/extension/extension.ts
  src/panel/pets.ts
Labels: hacktoberfest-accepted

#195 Add beach theme
  README.md
  media/backgrounds/beach/background-dark-large.png
  media/backgrounds/beach/background-dark-medium.png
  media/backgrounds/beach/background-dark-nano.png
  media/backgrounds/beach/background-dark.png
  media/backgrounds/beach/background-light-large.png
  media/backgrounds/beach/background-light-medium.png
  media/backgrounds/beach/background-light-nano.png
  media/backgrounds/beach/background-light.png
  media/backgrounds/beach/foreground-dark-large.png
  media/backgrounds/beach/foreground-dark-medium.png
  media/backgrounds/beach/foreground-dark-nano.png
  media/backgrounds/beach/foreground-dark.png
  media/backgrounds/beach/foreground-light-large.png
  media/backgrounds/beach/foreground-light-medium.png
  media/backgrounds/beach/foreground-light-nano.png
  media/backgrounds/beach/foreground-light.png
  media/main-bundle.js
  package.json
  screenshots/beach-pose.png
  src/common/types.ts
  src/extension/extension.ts
  src/panel/main.ts
Labels: hacktoberfest-accepted

#197 Add a custom hello message for cat
  src/panel/pets.ts
Labels: hacktoberfest-accepted

#196 Added method to randomise speed by +/- 30% to prevent pets from overlapping so much
  src/panel/pets.ts
Labels: hacktoberfest-accepted

#198 Added message from dog
  src/panel/pets.ts
Labels: hacktoberfest-accepted

#199 custom quote for tororo
  src/panel/pets.ts
Labels: hacktoberfest-accepted

#201 added rock message
  src/panel/pets.ts
Labels: hacktoberfest-accepted

#206 Added Duck Message
  src/panel/pets.ts
Labels: hacktoberfest-accepted

#207 Added message from Zappy
  src/panel/pets.ts
Labels: hacktoberfest-accepted

#208 Added Crab Message
  src/panel/pets.ts
Labels: hacktoberfest-accepted

#209 Added Clippy Message
  src/panel/pets.ts
Labels: hacktoberfest-accepted

#222 Add Code of Conduct
  .github/CODE_OF_CONDUCT.md
Labels: hacktoberfest-accepted

#220 docs: fleshed out installation and bug reporting
  README.md
Labels: hacktoberfest-accepted

#219 Added Two Cat Names
  src/common/names.ts
Labels: hacktoberfest-accepted

#231 Add portuguese translation to package.nls.json
  package.nls.pt.json
Labels: hacktoberfest-accepted

#234 Adding Thai translation
  package.nls.th.json
Labels: hacktoberfest-accepted

#233 Translate the basic strings file to French
  package.nls.fr.json
Labels: hacktoberfest-accepted

#236 Add new pet names
  src/common/names.ts
  src/panel/pets.ts
Labels: hacktoberfest-accepted

#239 Add danish translation
  package.nls.da.json
Labels: hacktoberfest-accepted

#244 Translate the basic strings to German
  package.nls.de.json
Labels: hacktoberfest-accepted

#245 Add new crab names
  src/common/names.ts
Labels: hacktoberfest-accepted

#247 Added pet names
  src/common/names.ts
Labels: hacktoberfest-accepted

#246 add Dutch json
  package.nls.nl.json
Labels: hacktoberfest-accepted

#248 add pet names
  src/common/names.ts
Labels: hacktoberfest-accepted

#265 feat: improve readability of readme documentation
  README.md
  screenshots/pet-select.png
Labels: hacktoberfest-accepted

#258 Add Romanian translation
  package.nls.ro.json
Labels: hacktoberfest-accepted, translations

#262 Add Polish translation
  package.nls.pl.json
Labels: hacktoberfest-accepted, translations

#253 Add Hindi translation
  package.nls.hi.json
Labels: translations

#270 Reduce code duplication on createPet function
  src/panel/pets.ts
Labels: hacktoberfest-accepted

#271 Improve Japanese translation
  package.nls.ja.json
Labels: hacktoberfest-accepted

#269 docs: add png for settings and fixed typos
  README.md
  screenshots/pet-remove.png
  screenshots/pet-roll-call.png
Labels: hacktoberfest-accepted

#268 Translate the basic strings to Italian
  package.nls.it.json
Labels: hacktoberfest-accepted

#266 Add Chinese Translation
  package.nls.zh.json
Labels: hacktoberfest-accepted

#273 Add my cats'names
  src/common/names.ts
Labels: hacktoberfest-accepted

#263 Update names.ts
  src/common/names.ts
Labels: hacktoberfest-accepted

#279 Enforce unique, sequential ID for pet names
  src/common/names.ts
Labels: hacktoberfest-accepted

#278 Add russian translation
  package.nls.ru.json
Labels: hacktoberfest-accepted

#284 Add new duck names
  src/common/names.ts
Labels: hacktoberfest-accepted

#285 Change PetCollection.pets to be a getter
  src/panel/main.ts
  src/panel/pets.ts
  src/test/suite/panel.test.ts
Labels: hacktoberfest-accepted

#286 Change relevant pet fields to getters
  src/panel/main.ts
  src/panel/pets.ts
  src/panel/states.ts
  src/test/suite/panel.test.ts
Labels: hacktoberfest-accepted

#287 Added new pet names
  media/main-bundle.js
  src/common/names.ts
Labels: hacktoberfest-accepted

#289 Add pet names
  src/common/names.ts
Labels: hacktoberfest-accepted

#290 Avoid `*` activating extension
  media/main-bundle.js
  package.json
  src/extension/extension.ts
Labels: hacktoberfest-accepted

#293 Updated name.ts
  src/common/names.ts
Labels: hacktoberfest-accepted

#294 adding white cat option
  media/cat/white_fall_from_grab_8fps.gif
  media/cat/white_idle_8fps.gif
  media/cat/white_land_8fps.gif
  media/cat/white_run_8fps.gif
  media/cat/white_swipe_8fps.gif
  media/cat/white_walk_8fps.gif
  media/cat/white_walk_fast_8fps.gif
  media/cat/white_wallclimb_8fps.gif
  media/cat/white_wallgrab_8fps.gif
  media/cat/white_with_ball_8fps.gif
  src/extension/extension.ts
Labels: hacktoberfest-accepted
